default_install_hook_types: [pre-commit, commit-msg, post-checkout, post-merge]

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.1.6'
  hooks:
  - id: ruff
  - id: ruff-format

- repo: https://github.com/python-poetry/poetry
  rev: '1.7.1'
  hooks:
  - id: poetry-check
  - id: poetry-lock
  - id: poetry-install