default_install_hook_types: [pre-commit, commit-msg, post-checkout, post-merge]

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.2.2'
  hooks:
  - id: ruff
  - id: ruff-format

- repo: https://github.com/pdm-project/pdm
  rev: '2.12.3'
  hooks:
  - id: pdm-sync
  - id: pdm-lock-check
