[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "terrible-tree"
version = "0.1.0"
description = "A dump and inefficient reimplmentation of the tree command, born out of pure boredome"
authors = ["Philipp Krueger"]
readme = "README.md"
license = "MIT"
packages = [{include = "terrible_tree", from = "src"}]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.scripts]
terrible-tree = "terrible_tree.__main__:main"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.292"
black = "^23.9.1"
isort = "^5.12.0"
pyright = "^1.1.331"
python-semantic-release = "^8.1.1"


[tool.ruff]
select = ["ALL"]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.semantic_release]
branch = "main"
verison_source = "tag"
tag_format = "v{version}"
commit_message = "ci: release v{version}"
build_command = "poetry build"
version_variables = [
    "src/terrible_tree/__main__.py:__version__"
]

version_toml = [
    "pyproject.toml:tool.poetry.version",
]

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
